/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data.structsher;
//import jaco.mp3.player.MP3Player;
//import jaco.mp3.*;
import java.io.File;
import java.lang.reflect.Array;
import java.util.*;
import java.lang.*;
import java.nio.file.Paths;
import static javafx.scene.input.KeyCode.M;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author kcsstore.com
 */
public class video extends javax.swing.JFrame {
    NewClass Videos= new  NewClass();
    int x;
    int y;
    

    /**
     * Creates new form video
     */
    public video() {
        initComponents();
         AllVideos.setModel(new DefaultComboBoxModel<>( NewClass.videoNames));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AllVideos = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        playlistScreen = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        VideoName = new javax.swing.JLabel();
        Playetat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        textname = new javax.swing.JTextField();
        textlink = new javax.swing.JTextField();
        Setting = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(null);

        AllVideos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(AllVideos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 370, 370, 340);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Add video->>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 410, 120, 25);

        playlistScreen.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(playlistScreen);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(850, 250, 410, 450);

        jButton2.setText("play");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 490, 120, 25);

        jButton3.setText("End");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(690, 490, 130, 25);

        jButton4.setText("search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(410, 170, 71, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("search by  name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 165, 140, 30);
        getContentPane().add(VideoName);
        VideoName.setBounds(140, 90, 460, 30);

        Playetat.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Playetat.setForeground(new java.awt.Color(255, 255, 255));
        Playetat.setText("stopped");
        getContentPane().add(Playetat);
        Playetat.setBounds(20, 80, 130, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("search by link");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 200, 110, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("search by gool");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 240, 130, 30);

        jLabel4.setBackground(new java.awt.Color(102, 102, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("search by red card");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 285, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("search by yellow card");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 320, 180, 30);

        jButton5.setText("search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(410, 210, 71, 25);

        jButton6.setText("search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(270, 250, 71, 25);

        jButton7.setText("search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(270, 330, 71, 25);

        jButton8.setText("search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(270, 290, 71, 25);
        getContentPane().add(textname);
        textname.setBounds(240, 170, 120, 22);
        getContentPane().add(textlink);
        textlink.setBounds(239, 210, 120, 22);
        getContentPane().add(Setting);
        Setting.setBounds(20, 130, 1240, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Video Player");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 10, 260, 70);

        jButton9.setText("Move Up");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(430, 640, 120, 25);

        jButton10.setText("Move Down");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(689, 640, 120, 25);

        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(570, 570, 120, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/maxresdefault.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -10, 1280, 720);

        setSize(new java.awt.Dimension(1300, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           try{
         NewClass.playlist[( Videos.cntPlay)].player.stop();
        int beg =  Videos.getBeginning();
        
        Playetat.setText("Playing:");
        VideoName.setText( Videos.playlist[beg].fileName);
         Videos.playlist[beg].player =  Videos.playlist[beg].GetVideoplayer();
         Videos.playlist[beg].player.addToplaylist( Videos.playlist[beg].videofile);
         Videos.playlist[beg].currentPath = Paths.get(".").toAbsolutePath().normalize().toString();
         Videos.playlist[beg].player.play();
        }
        catch(NullPointerException e){
             JOptionPane.showMessageDialog(null,"There is no video in list");
        }
        
        
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           String abs = (String) AllVideos.getSelectedValue();
        NewClass.addVideo(abs);
        
      playlistScreen.setModel(new DefaultComboBoxModel<>(NewClass.playlistName));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //  try{
        //songs.playlist[(songs.cntPlay)].player.stop();
        //int beg = songs.getEnd();
        
        //Playetat.setText("Playing:");
        //VideoName.setText(songs.playlist[beg].fileName);
        //songs.playlist[beg].player = songs.playlist[beg].GetMp3player();
        //songs.playlist[beg].player.addToPlayList(songs.playlist[beg].videofile);
        //songs.playlist[beg].currentPath = Paths.get(".").toAbsolutePath().normalize().toString();
        //songs.playlist[beg].player.play();
        //}
        //catch(NullPointerException e){
        //     JOptionPane.showMessageDialog(null,"There is no songs in list");
        //}
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         try{
        NewClass.playlist[( Videos.cntPlay)].player.stop();
        Playetat.setText("Stopped:");
        VideoName.setText(" ");        
        int mv = playlistScreen.getSelectedIndex();
         Videos.moveDown(mv);
        
      playlistScreen.setModel(new DefaultComboBoxModel<>(NewClass.playlistName));
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Select a song");
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Playlist is empty");    
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try{
        NewClass.playlist[( Videos.cntPlay)].player.stop();
        Playetat.setText("Stopped:");
        VideoName.setText(" ");
        int mv = playlistScreen.getSelectedIndex();
         Videos.moveUp(mv);
        
      playlistScreen.setModel(new DefaultComboBoxModel<>(NewClass.playlistName));
    }
     catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Select a video");
        }
     catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Playlist is empty");    
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
           try{ 
        int Dindx = playlistScreen.getSelectedIndex();
           if(Dindx == 0 &&  Videos.cnt == 1) {
                 Videos.playlist[0].player.stop();
                Playetat.setText("Stopped:");
                VideoName.setText(" ");
           } 
            Videos.deletevideo(Dindx);
      playlistScreen.setModel(new DefaultComboBoxModel<>(NewClass.playlistName));
        }
        catch(NullPointerException | ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Playlist is empty");    
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String nGet = textname.getText(); 
        String Namevideo =  Videos.searchSongName(nGet);
         playlistScreen.setModel(new DefaultComboBoxModel<>(NewClass.playlistName));

            JOptionPane.showMessageDialog(null, Namevideo);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          String nGet = textlink.getText(); 
        String NameSong =  Videos.searchSongName(nGet);
         playlistScreen.setModel(new DefaultComboBoxModel<>(NewClass.playlistName));

            JOptionPane.showMessageDialog(null, NameSong);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         // String nGet = textgool.getText(); 
        String Namevideo =  Videos.searchvideogool("gool");
         playlistScreen.setModel(new DefaultComboBoxModel<>(NewClass.playlistName));

            JOptionPane.showMessageDialog(null, Namevideo);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //  String nGet =  .getText(); 
        String Namevideo =  Videos.searchvideoredcard("red");
         playlistScreen.setModel(new DefaultComboBoxModel<>(NewClass.playlistName));

            JOptionPane.showMessageDialog(null, Namevideo);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //  String nGet = textyellow.getText(); 
        String Namevideo =  Videos.searchvideoyellowcard("yellow");
         playlistScreen.setModel(new DefaultComboBoxModel<>(NewClass.playlistName));

            JOptionPane.showMessageDialog(null, Namevideo);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new video().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList AllVideos;
    private javax.swing.JLabel Playetat;
    private javax.swing.JLabel Setting;
    private javax.swing.JLabel VideoName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList playlistScreen;
    private javax.swing.JTextField textlink;
    private javax.swing.JTextField textname;
    // End of variables declaration//GEN-END:variables
}
